apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: redis  
spec:
 containers: 
 - name: app1 
   image: supergiantkir/animals:bear
   volumeMounts:
    - name: redis-persistent-storage
      mountPath: /storage
 - name: app2
   image: yanivomc/spring-music:latest
   volumeMounts:
    - name: redis-persistent-storage
      mountPath: /storage
  volumes:
  - name: app-storage
    hostPath:
      path: /tmp/files
